/**
 * Vercel API Route for robots.txt
 * This bypasses all static file restrictions and guarantees 200 responses
 */

export default function handler(req, res) {
  // Log the request for debugging
  console.log(`[ROBOTS] Request from: ${req.headers['user-agent'] || 'Unknown'}`);
  console.log(`[ROBOTS] IP: ${req.headers['x-forwarded-for'] || req.connection.remoteAddress}`);
  console.log(`[ROBOTS] Method: ${req.method}`);
  
  // Handle OPTIONS requests (preflight)
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, HEAD, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', '*');
    res.setHeader('Access-Control-Max-Age', '86400');
    return res.status(200).end();
  }
  
  // Set comprehensive headers for maximum compatibility
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=3600, s-maxage=3600');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, HEAD, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', '*');
  res.setHeader('Vary', 'User-Agent, Accept');
  res.setHeader('X-Robots-Tag', 'noindex'); // Don't index the API endpoint itself
  
  // Robots.txt content
  const robotsContent = `User-agent: *
Allow: /

# Sitemap
Sitemap: https://thequasarconsultants.com/sitemap.xml

# Crawl-delay
Crawl-delay: 1

# Allow common SEO audit tools
User-agent: Screaming Frog SEO Spider
Allow: /

User-agent: AhrefsBot
Allow: /

User-agent: SemrushBot
Allow: /

User-agent: MJ12bot
Allow: /

User-agent: DotBot
Allow: /

User-agent: SitebulbBot
Allow: /

User-agent: SEOkicks
Allow: /

User-agent: LinkdexBot
Allow: /

User-agent: MajesticSEO
Allow: /

# Generated by API route at ${new Date().toISOString()}`;

  // Return 200 response with robots.txt content
  return res.status(200).send(robotsContent);
}
